### ISSUE TITLE
Module 7 demo is redundant

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftLearning/20778-Analyzing-Data-with-Power-BI#18]
Students have already seen how to connect to the same Azure SQL database in Module 6. They've also already seen relationship configuration in Module 5. So this demo as written does not introduce any new concepts and is thus of little interest to students.

Suggest making the demo relevant to the material introduced in this module. For example, show DirectQuery, show differences in Power BI platform's behaviour between Import/DirectQuery/Live modes, show composite models, etc.

**Comment by markfitzqa** [comment]
vitaly-livshits - I agree that the lab needs replacing, but so do all the other labs.  All of your suggestions are equally valid as the delegates want more than the same simple labs repeated.  The issue that the courseware developers have is that there are so many new features (since Jan 2018) that are not in the product the manual and slides would also need updating.  This will not be done anytime soon.

**Comment by GeoffAllix** [comment]
As Mark has said, we have limited ability to change the demos and labs (we're only supposed to perform fixes). Having said that, I have modified this demo so that it has a composite storage mode. This should allow an instructor to discuss this in more depth even though it hasn't been covered in the manual.

**Comment by AndyFogg** [comment]
Closed as per above comments.

**Comment by vitaly-livshits** [comment]
@markfitzqa 

> I agree that the lab needs replacing, but so do all the other labs.
All other labs need replacing? How so? Can you please be specific?

>  the delegates want more than the same simple labs repeated
Well, we are 100% in agreement here. What's the reason for the pushback then? The suggestions represent very simple tweaks. We are probably talking < 1 hour of effort to make an amazing lab out of them. One that's truly rewarding to complete and one that students will appreciate and learn from.

>  The issue that the courseware developers have is that there are so many new features (since Jan 2018) that are not in the product the manual and slides would also need updating
Is this a generic statement or is it in response to the specific feedback in this issue? None of the suggestions in this thread except 1 (composite models) are "new features since Jan 2018". They've been in Power BI forever. They are already in the course too.
